### ISSUE TITLE
Organization Details

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Roadmap#1]
We need to put some things together:
- [x] Description
- [x] Logo
- [x] Website
- [x] Gitter

For logos, please make sure you include a description of what it is, the licensing, and a source file which is a high resolution and contains as much vector graphics as possible. These will be necessary for re-using the logo in many different ways, and for properly attributing the work.

**Comment by ChrisRackauckas** [comment]
Possible logo?

![juliadiffeq](https://cloud.githubusercontent.com/assets/1814174/18193813/f3796b3e-7095-11e6-8422-abaab02ca974.png)

**Comment by ChrisRackauckas** [comment]
Logo idea:

![juliadiffeq](https://cloud.githubusercontent.com/assets/1814174/18194096/1063c92c-7098-11e6-9ce9-30220dd6dc55.png)

**Comment by ChrisRackauckas** [comment]
Or a black background:

![juliadiffeqblack](https://cloud.githubusercontent.com/assets/1814174/18194185/b66fcaaa-7098-11e6-8f04-a154d45deeff.png)

@Ismael-VC 's idea:

![blob](https://cloud.githubusercontent.com/assets/1814174/18194200/da627962-7098-11e6-9e9a-c0f2dc1a066e.png)

Kudos to @geekyl for the idea to use Chaoscope.

**Comment by pwl** [comment]
Where can I get the circles from Julia logo from?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/julialang.github.com/blob/master/_includes/logo.svg

**Comment by pwl** [comment]
How about this one:

![julia](https://cloud.githubusercontent.com/assets/72500/18203689/ca3127b6-7118-11e6-9740-ef1e61d1704a.png)

**Comment by ChrisRackauckas** [comment]
I don't know if that logo would do well as a square. It would be a good web header though.

**Comment by pwl** [comment]
Maybe something in the lines of https://en.wikipedia.org/wiki/File:String_wave_2.svg

It looks dynamic and represents a solution to a PDE

EDIT: or maybe something like https://duckduckgo.com/?q=pendulum+phase+space&t=ffab&iax=1&ia=images

EDIT2: This one looks aesthetically pleasing https://en.wikipedia.org/wiki/File:Separatrix_for_a_Simple_Pendulum.png (we could add a little bit of damping to make it less symetrical and we should remove the axes)

**Comment by ChrisRackauckas** [comment]
Here's banner versions of the attractor idea. It definitely looks a lot better on a dark background than a light background. We'll see what other ideas people come up with. 

@pwl any specific PDE in mind?

![juliadiffeqlarge](https://cloud.githubusercontent.com/assets/1814174/18203904/aa688c8e-70ce-11e6-8858-4ce6bec81b6c.png)

![juliadiffeqlargewhite](https://cloud.githubusercontent.com/assets/1814174/18203905/accf8824-70ce-11e6-826b-cea4bb15502c.png)

**Comment by pwl** [comment]
@ChrisRackauckas A simple wave equation would do.  It has to be something simple for people to recognize.  Also check out the phase space ideas I posted.

**Comment by ChrisRackauckas** [comment]
Could you do a mockup?

**Comment by pwl** [comment]
I already posted it: https://en.wikipedia.org/wiki/File:String_wave_2.svg (this is obviously not done by me)

Just remove the arrows and the axes.

**Comment by ChrisRackauckas** [comment]
I'm not seeing your vision. What's the square and the banner form? Are you incorporating the Julia colors?

**Comment by pwl** [comment]
Right, I forgot about the Julia colors.  Behold:

![string_wave_2 svg](https://cloud.githubusercontent.com/assets/72500/18204633/182196c2-711e-11e6-9f4d-47ac98c055c8.png)

Admittedly, this was looking better in my head:-)

EDIT: this is just rescaled version of the image from Wikipedia, we should make something like that ourselves.

**Comment by ChrisRackauckas** [comment]
Could you put up a bigger version? It looks pretty good.

**Comment by pwl** [comment]
Following up on the same idea:

![string_wave_300 svg](https://cloud.githubusercontent.com/assets/72500/18204814/fee06e58-711e-11e6-86eb-168afbca370e.png)

or:

![string_wave_2 svg](https://cloud.githubusercontent.com/assets/72500/18204823/11ee003c-711f-11e6-8caa-f46c282f73d7.png)

**Comment by ChrisRackauckas** [comment]
That came out pretty nice. Can I get the source for that?

**Comment by mauro3** [comment]
I also thought about using a strange attractor, but could not find one with three lobes. Does anyone know one?

**Comment by ChrisRackauckas** [comment]
I couldn't find one. But you can poke around Chaoscope and see if you get one. Just poke around Chaoscope anyways, it's pretty fun!

**Comment by mauro3** [comment]
I guess we just got to find one: http://www.chaoscope.org/tutorials/search.htm, apparently it's like digging for gold.

**Comment by ChrisRackauckas** [comment]
I asked a few people and it looks like so far @pwl 's design is in the lead. However, please share the vector graphic source. From the chat channels it seems there may be a few more submissions coming. 

I also lightened the bottom colors for mine:

![juliadiffeq](https://cloud.githubusercontent.com/assets/1814174/18225878/4a21132e-71b3-11e6-8ef0-88b0ee6515c6.png)

We can be really official and use the extra logos as logos for the packages. :+1:

**Comment by neomatrixcode** [comment]
my proposal:

![propuesta1](https://cloud.githubusercontent.com/assets/8965843/18229262/09053eb2-7238-11e6-8ade-14ad59d527f4.png)

![propuesta2](https://cloud.githubusercontent.com/assets/8965843/18229264/17973a02-7238-11e6-91d4-127c47af0bd2.png)

![propuesta3](https://cloud.githubusercontent.com/assets/8965843/18229266/1e115c1e-7238-11e6-9374-be42e5bd9577.png)

**Comment by ChrisRackauckas** [comment]
Woooh. Those are really cool. Can you share the SVGs? (It looks like the font is blurred on the edges in the PNGs).

Also, could you share what you're plotting? I've never seen those before!

**Comment by neomatrixcode** [comment]
reuploading

![propuesta1](https://cloud.githubusercontent.com/assets/8965843/18229325/c55b8204-723a-11e6-9c5b-27c7e1007292.png)

![propuesta2](https://cloud.githubusercontent.com/assets/8965843/18229326/c9d04e64-723a-11e6-8cc1-c924b3280860.png)

![propuesta3](https://cloud.githubusercontent.com/assets/8965843/18229327/d557a034-723a-11e6-8206-d19385a0ffff.png)

**Comment by neomatrixcode** [comment]
I have no svg files, just a psd file.
https://drive.google.com/open?id=0B7FTOk3aA5m-b3RWeHZUM2dPUEk

Try to convert one of the png to svg, but has no color.

https://drive.google.com/open?id=0B7FTOk3aA5m-U3hEbF9iOUd2RzQ

**Comment by ChrisRackauckas** [comment]
PSD is fine, but it looks like the version you gave has already squashed all the layers. What I meant was I am looking for a version with as high-quality as possible for the rasters, and vector graphics whenever possible (i.e. the text. and the picture if possible, it's likely those the originals there are rasters?). This will help with future edits like resizing, adding transparency, finding out what font was used, etc. 

[Note that file size doesn't matter because the original will be saved separately on the site, and displayed versions will be cut down from it.]

Also, to put it out there, my vote is on the middle one.

**Comment by ChrisRackauckas** [comment]
Also, is there any way for the bottom right circle to be purple, to match the Julia logo? I'm not sure if it's possible given the dark background, but it's worth trying.

**Comment by neomatrixcode** [comment]
ok, no problem increasing the size of the image and change the color

**Comment by ChrisRackauckas** [comment]
For reference, here's the source for the ones I made. Note that I included the SinhalaMN font which I used. I got the idea from BioJulia, and it matches the Julia logo vector graphic pretty well. I included the chaoscope saves too.

[juliadiffeq_possiblelogo.zip](https://github.com/JuliaDiffEq/Roadmap/files/453806/juliadiffeq_possiblelogo.zip)

**Comment by neomatrixcode** [comment]
Thank you

**Comment by cormullion** [comment]
Looks like you've got plenty of winners here already! After looking at all the other organisations, I like the way most of them just make a simple mod to the three circles logo, rather than try anything too complicated (although there are a few exceptions!).

I went for a simple abstract design to fit into a square, mostly forgetting about Lorenz and butterflies, sadly...

![diffeq-test](https://cloud.githubusercontent.com/assets/52289/18229508/d09ecf84-7273-11e6-8d02-bfc8fd9b7ff1.png)

(source [here](https://gist.github.com/cormullion/114a37f418237a11308d8b617224e7f0))

**Comment by Ismael-VC** [comment]
About the font:
- https://groups.google.com/forum/m/#!topic/julia-users/T80CzzznFyI

> The font situation is a bit odd. The name of the font is called Sinhala MN Bold. It has shipped with OS X since Lion and provides glyphs for the Sinhalese language. The characters used in this text, however, are plain old ASCII and clearly not in Sinhalese. I have no idea what the "fallback font" used in Sinhala MN Bold is, although it is the same as used on many other non-english fonts on OS X. I tried to dig into it, but can't figure it out. The sharply slanted letter tops are very distinctive and should be easy to identify if someone happens to know the original font. I chose this style by just trying various fonts available on my system and seeing what looked good. This one just seemed to work.
> 
> Regarding licensing of the Sinhala MN Bold font, it's pretty clear that all documents created using fonts distributed with OS X may be used without any additional licensing, so this is fine (if we wanted to distributed or modify the font itself, that would be a different story).

-- Stefan K.

**Comment by pwl** [comment]
All glory to the hypnotoad!  But I like the way where this is going.  What
do you think about a julia colored version of the bottom picture from here
http://www.scholarpedia.org/article/File:Fig1.gif

Sorry for poor formatting, I'm on a mobile.

**Comment by cormullion** [comment]
It's not a fallback font, it's the design for the Latin part of this family of fonts.

> The font used for the logo's original design is generally known as MN Latin. MN is Muthu Nedumaran, of Murasu Systems. Muthu Nedumaran developed several Indic fonts which are currently bundled with Mac OS X: Bangla MN, Gurmukhi MN, Kannada MN, Khmer MN, Lao MN, Malayalam MN, Myanmar MN, Oriya MN, Sinhala MN, Tamil MN, and Telugu MN. The Latin (ie Western/Roman) character designs for all these fonts use the same distinctive "serifless Times Roman" style.

**Comment by cormullion** [comment]
I went on wikipedia to find out what a differential equation was. Best bit was finding all these blokes with wigs:

![screen shot 2016-09-04 at 17 51 24](https://cloud.githubusercontent.com/assets/52289/18232475/42f49a10-72c8-11e6-8ff3-1cab82c8c51b.png)

;)

**Comment by pwl** [comment]
That is hilarious, +1

**Comment by neomatrixcode** [comment]
I changed the color

![juliadiff2](https://cloud.githubusercontent.com/assets/8965843/18232624/44229f74-7299-11e6-90ac-437f752b12e6.jpg)

![propuesta3](https://cloud.githubusercontent.com/assets/8965843/18232626/4bc9586c-7299-11e6-8ad9-c10fe9795bda.jpg)

in this folder are the svg images:
https://drive.google.com/open?id=0B7FTOk3aA5m-X2VLU2taVHlWU2c

**Comment by ChrisRackauckas** [comment]
I think the one you have on top there is perfect. But I'll take the entries and put them to a poll next week, and we'll see what happens.

The text still shows up as a raster in the PSD. Did you get it from my example? If so, then we're going to want to replace the picture of the text with the vector graphics of the text (contained in the Illustrator file in the .zip I linked). I can look into it later if no one else gets to it.

**Comment by neomatrixcode** [comment]
you can use the file extension .ai

**Comment by ChrisRackauckas** [comment]
Perfect!

**Comment by cormullion** [comment]
Did another one with different squiggles.

![screen shot 2016-09-04 at 19 35 10](https://cloud.githubusercontent.com/assets/52289/18233145/13d423b8-72d7-11e6-8b7a-b66b6c626ee7.png)

although looks like an ECG machine... :) 

(source [here](https://gist.github.com/cormullion/ed9c3ff82844a4ea60388c9e6bd81632))

**Comment by mauro3** [comment]
I like the top one in https://github.com/JuliaDiffEq/Roadmap/issues/1#issuecomment-244585482. Presumably this is a Poincaré map, of what?  (the bottom two are too complex, not simple enough).

**Comment by pwl** [comment]
![logo svg](https://cloud.githubusercontent.com/assets/72500/18308159/a88a716a-74f3-11e6-8710-f9fb8a1e28b2.png)
EDIT: rotated to fit the canonical Julia triangle.  Changing the colors of the paths seems like a lot of work, so I will leave them as black for the time being.

EDIT2: this was shamelessly stolen from a book, if we want to keep it we should ask the authors for a permission or draw the plot from scratch ourselves.  This is some kind of a phase plane for a time-dependent system, which is given explicitly, so reproducing this plot shouldn't be extremely difficult.

**Comment by mauro3** [comment]
That is very nice too.  (Needs 120deg rotation, green should be at the top)

**Comment by ChrisRackauckas** [comment]
Please move the logo discussion to #3. The last thing to discuss here is the website.
