### ISSUE TITLE
Logo Poll

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/Roadmap#3]
Welcome to the JuliaDiffEq Official Logo Poll! To start I will be posting the some of the entries from #1. Late entries are allowed: please post the logo idea as a jpeg/png, but also include a source (to a vector image if applicable, so in the future it can be resized). On these additional entries, I will move them up as the next option and they will join the others for the remaining time period.

Note that this is voting on the idea and not the complete logo: they will all be completed with some form of the Julia DiffEq text (feel free to leave a comment if you have any suggestions on that)

Use the reactions to vote on which logos you think are best. You may vote for as many entries as you like. We will close the polls on 9/24/2016. Have fun!

**Comment by ChrisRackauckas** [comment]
### Option 1

By @cormullion. Vote by using a :+1:  (+1).

![d09ecf84-7273-11e6-8d02-bfc8fd9b7ff1](https://cloud.githubusercontent.com/assets/1814174/18456766/6c1a6f28-7908-11e6-993a-48fb91fb6ad2.png)

### Option 2

By @codeneomatrix. Vote for it by using a :-1: (-1).

![c55b8204-723a-11e6-9c5b-27c7e1007292](https://cloud.githubusercontent.com/assets/1814174/18456765/68d4c85e-7908-11e6-9715-1de609e6db24.png)

### Option 3

By @pwl . Vote for it by using a :laughing: (laughing).

![a88a716a-74f3-11e6-8710-f9fb8a1e28b2](https://cloud.githubusercontent.com/assets/1814174/18456764/6622de52-7908-11e6-964d-c95925e45334.png)

### Option 4

By @codeneomatrix. Vote for it by using a :hooray: (hooray)

![44229f74-7299-11e6-90ac-437f752b12e6](https://cloud.githubusercontent.com/assets/1814174/18456763/63d12794-7908-11e6-8cea-3f3d3eb57ffe.jpg)

### Option 5

By @cormullion. Vote by using a :confused: :  (confused).

![13d423b8-72d7-11e6-8b7a-b66b6c626ee7](https://cloud.githubusercontent.com/assets/1814174/18456762/60ac34f0-7908-11e6-8f18-cc9ef0fa993c.png)

### Option 6

By @ChrisRackauckas. Vote for it by using a :heart: (heart).
![4a21132e-71b3-11e6-8ef0-88b0ee6515c6](https://cloud.githubusercontent.com/assets/1814174/18456757/5bd3e8ce-7908-11e6-93d3-7de9f32f1e4b.png)

**Comment by ChrisRackauckas** [comment]
### Option 7

By @codeneomatrix. Vote for it by using a :+1: (+1).

![4bc9586c-7299-11e6-8ad9-c10fe9795bda](https://cloud.githubusercontent.com/assets/1814174/18456759/5d775ae4-7908-11e6-9bf0-4fbd14d62184.jpg)

### Option 8

By @pwl. Vote for it by using a :-1: (-1)

![11ee003c-711f-11e6-8caa-f46c282f73d7](https://cloud.githubusercontent.com/assets/1814174/18456868/5da10208-7909-11e6-923d-0f34814fa98d.png)

**Comment by WEBEXZ** [comment]
(hooray) Option 4 By @codeneomatrix.

**Comment by cortner** [comment]
I like Option 8 without the Julia dots.

**Comment by cormullion** [comment]
Nice job on the GitHub Poll Hack, @ChrisRackauckas ... :)

**Comment by pwl** [comment]
How about we use two different logos: one for the main page and one for the avatar?

**Comment by ChrisRackauckas** [comment]
That is an option, but I think it's usually best to stick to one. That doesn't mean we can't have another picture floating around the website or something, but there really should only be one that we call our logo or else it gets confusing.

That doesn't mean we can choose logos for the individual packages. I mean, Sundials has a logo. It'd be pretty boss if we sported logos in the ODE.jl and DifferentialEquations.jl documentations as well.

**Comment by cormullion** [comment]
I knocked up a Julia script to draw the current hot favourite (option 3) to a close approximation. It might be useful—at least until you get hold of the original code to plot it directly.

![screen shot 2016-09-14 at 11 34 08](https://cloud.githubusercontent.com/assets/52289/18509219/5f44f63e-7a6f-11e6-905f-8776ce290d5e.png)

source [here](https://github.com/cormullion/julia-logo-graphics/blob/master/src/diffeq-logo.jl)

**Comment by pwl** [comment]
It doesn't seem to scale very well, maybe the smallest picture should have the black lines removed and we should only keep the colored parts, perhaps with a thick boundary around the colors to mimic the Julia circles.  I will not have much time this week but I will try to modify it slightly (and I will upload the svg file...).

**Comment by cortner** [comment]
I think this is beautiful but gets too busy when you make it small. This is why I prefer Option 8. (same reason I suggested to remove the Julia dots)

**Comment by cormullion** [comment]
Simpler logos can be better. Designs should always be evaluated in a range of sizes - what looks great in a PDF in a big window can look too confusing or cluttered when scaled down to a small bitmap.

**Comment by ChrisRackauckas** [comment]
I think simpler versions / different variations of the same logo would be fine for different uses (that's why having a source which generates it or a vector graphic source is necessary). But I don't think like having Option 8 for thumbnails and Option 3 for the website is a good idea: it's too confusing / fragmented.

**Comment by ChrisRackauckas** [comment]
Congrats @pwl. Your design (Option 3) has been chosen! Play around with making compact / less compact versions, and upload .svg's when you're ready. (Make some versions with the JuliaDiffEq letters. You might want to play with the font attributes a little bit more: it looks to be the right font, but maybe it's a bit off on the widths).

**Comment by ChrisRackauckas** [comment]
How's the logo editing going?

**Comment by pwl** [comment]
Unfortunately looks like I lost the original logo that I used to create the png file.  I must have saved later edits on top of it.  But I managed to simplify what was left of it to this: https://www.dropbox.com/s/x2xew1169u4f1wc/JuliaDiffEq_icon.svg?dl=0.  I think it's current form would make a good icon for the org (feel free to play around with the thickness of the boundaries).  I will try to recreate the original one if you want it for the webpage.

**Comment by ChrisRackauckas** [comment]
I actually really like it. It still captures the idea of diffeqs / flows very well, even without the flow lines, and it's nice and simple. I'll let others chime in. Note that Github slightly cuts it off on the sides with its available bounding boxes: maybe it should be made square? Right now it's ever-so-slightly not square.

**Comment by ChrisRackauckas** [comment]
I fixed the logo's proportions in an illustrator file. The SVG had some small errrors that I didn't take care of around some of the edges (which were cutoff before, but now slightly visible). I will add the AI file to some repo soon (and distribute some raster renders), and whoever wants to take a stab at fixing the little edge problems can. But I think it looks really good!

**Comment by neomatrixcode** [comment]
hi, I made this, hope it helps.
https://drive.google.com/open?id=0B7FTOk3aA5m-MkxCU3FXZFRnYmM

**Comment by pwl** [comment]
@codeneomatrix thanks!  This could be potentially useful for the webpage, once it's up.
