### ISSUE TITLE
Move PR49 to JuliaDiffEq

### ISSUE THREAD

**Issue by pwl** [JuliaDiffEq/Roadmap#7]
@mauro3, as @ChrisRackauckas suggested we should move PR49 to JuliaDiffEq to generate more exposure.  There are potential opportunities of getting new people involved in this package and we are missing out on them.

- [ ] update the README
- [ ] figure out the name (most likely candidate is `ODEIterators.jl`)
- [ ] clean up the docs (by this I mean remove the chapters that are not yet written)?
- [x] detach from ODE.jl
- [ ] anything else?

As for the name, @ChrisRackauckas suggested `ODEIterators.jl`, which sounds fine.  We could also consider `ODEInterfaces.jl` if we aim higher with the scope of the package.

**Comment by ChrisRackauckas** [comment]
Not `ODEInterfaces`. There's already `ODEInterface` which is well-established. That's pretty confusing.

**Comment by pwl** [comment]
True, I had a feeling that I heart the name somewhere:-).  Any other propositions?

**Comment by mauro3** [comment]
How about we name it `Pr49.jl`?  No, more seriously, leave it as ODE.jl and have an ODElegacy.jl.

**Comment by mauro3** [comment]
Actually how about we do name it PR49.jl for now and move it to JuliaDiffEq.  Once it is ready we can ponder the names more.

**Comment by musm** [comment]
just a quick fyi PR49.jl would with very high probability (a.s 1) not pass through tony over at METADATA.jl

**Comment by mauro3** [comment]
Yes Tony wouldn't like that.  But, sorry, I wasn't clear.  I meant to use PR49.jl as an interim name to allow moving https://github.com/JuliaODE/ODE.jl to this organization (ODE.jl exists already).  Once we decide it was ready to register in METADATA.jl, we'd need to find another name.

**Comment by pwl** [comment]
Yeah, a PR49.jl working name would be fine.  Is there any way to remove the "fork" status from PR49?  If we plan to replace ODE.jl with PR49.jl we shouldn't have a "fork" status on the replacement package, otherwise it will be seen as a fork of ODELegacy.jl.  Or maybe even a fork itself (ODE.jl) after the name change?

**Comment by ChrisRackauckas** [comment]
> Yeah, a PR49.jl working name would be fine. Is there any way to remove the "fork" status from PR49? If we plan to replace ODE.jl with PR49.jl we shouldn't have a "fork" status on the replacement package, otherwise it will be seen as a fork of ODELegacy.jl. Or maybe even a fork itself (ODE.jl) after the name change?

Looks like that has an easy fix:

http://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

**Comment by pwl** [comment]
As of now, PR49.jl is detached from ODE.jl.

**Comment by mauro3** [comment]
I guess my idea of keeping ODE.jl as name and moving the old to LegacyODE.jl was not too popular...

**Comment by pwl** [comment]
@mauro3 I like this idea, that's why I detached PR49.  A repo replacing ODE shouldn't be its fork and there is almost nothing left of the old ODE in PR49.  In the meantime we can keep a working name like PR49 or ODEIterators.

**Comment by mauro3** [comment]
Ok, I guess that should work.  Tnx!

**Comment by pwl** [comment]
So, how about we move PR49 to JuliaDiffEq now, as `PR49.jl`, without registering it as a package (the name wouldn't pass the METADATA standards).  Then we could think about fixing the remaining issues and use it to replace ODE.jl.

**Comment by pwl** [comment]
Is anybody against the name `ODEIterators`?

**Comment by mauro3** [comment]
:+1: but I'm not sure it passes the strict naming conventions.  But we can cross that bridge when we get there.

**Comment by ChrisRackauckas** [comment]
>👍 but I'm not sure it passes the strict naming conventions. But we can cross that bridge when we get there.

Yeah, I'm not entirely sure of a sane way to name it that passes the naming conventions...
